// Comentário de linha única
/*
comentário de múltiplas linhas
*/

var idade;
console.log(50*50);
console.log(50/50);
console.log(50**50);
console.log(Math.floor(7 / 2));
console.log (2+1)
console.log (2-1)
console.log (idade%2)
console.log (idade === 16)
console.log (20 > 30)
console.log (20 < 30)
console.log (20 == 20)
console.log ('Thomazx7' == 'Thomazx7')
console.log (20 != 20)
document.querySelector("h1")
